// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // entity_obj
global.__objectDepths[1] = 0; // entityLocal_obj
global.__objectDepths[2] = 0; // entityNetwork_obj
global.__objectDepths[3] = 0; // entityNetworkPrime_obj
global.__objectDepths[4] = 0; // entityNetworkShadow_obj
global.__objectDepths[5] = 0; // Movable_obj
global.__objectDepths[6] = 0; // Collidable_obj
global.__objectDepths[7] = 0; // CollidingMover_obj
global.__objectDepths[8] = 0; // CollidingMoverTest_obj
global.__objectDepths[9] = 0; // CollidingMoverWallCollider_obj
global.__objectDepths[10] = 0; // MovableTest_obj
global.__objectDepths[11] = 0; // entityCombatant_obj
global.__objectDepths[12] = 0; // entityCombatantShadow_obj
global.__objectDepths[13] = 0; // entityCombatantFriendly_obj
global.__objectDepths[14] = 0; // playerBase_obj
global.__objectDepths[15] = 0; // playerBasic_obj
global.__objectDepths[16] = 0; // player1_obj
global.__objectDepths[17] = 0; // player1Test_obj
global.__objectDepths[18] = 0; // entityCombatantEnemy_obj
global.__objectDepths[19] = 0; // entityCombatantEnemyShadow_obj
global.__objectDepths[20] = 0; // entityEnemyTest_obj
global.__objectDepths[21] = 0; // projectileBase_obj
global.__objectDepths[22] = 0; // projectileFriendly_obj
global.__objectDepths[23] = 0; // projectileEnemy_obj
global.__objectDepths[24] = 0; // projectileEnemyShadow_obj
global.__objectDepths[25] = 0; // projectileFriendlyShadow_obj
global.__objectDepths[26] = 0; // projectileTick_obj
global.__objectDepths[27] = 0; // projectileShotgunPellet_obj
global.__objectDepths[28] = 0; // projectileSpinner_obj
global.__objectDepths[29] = 0; // projectileHour_obj
global.__objectDepths[30] = 0; // projectileBaddieBasic_obj
global.__objectDepths[31] = 0; // projectileBulletBase_obj
global.__objectDepths[32] = 0; // projectileBulletHighSpeedBase_obj
global.__objectDepths[33] = 0; // projectileTest_obj
global.__objectDepths[34] = 0; // projectileHighSpeedTest_obj
global.__objectDepths[35] = 0; // projectileHighSpeedInvisible_obj
global.__objectDepths[36] = 0; // projectileLaserBase_obj
global.__objectDepths[37] = 0; // projectileLaser_obj
global.__objectDepths[38] = 0; // projectileLaserBeamBase_obj
global.__objectDepths[39] = 0; // interactibleShadow_obj
global.__objectDepths[40] = 0; // interactibleBase_obj
global.__objectDepths[41] = 0; // item_obj
global.__objectDepths[42] = 0; // itemPassiveBase_obj
global.__objectDepths[43] = 0; // passiveDrumMag_obj
global.__objectDepths[44] = 0; // passivePurplePowder_obj
global.__objectDepths[45] = 0; // passiveAlienAutopsy_obj
global.__objectDepths[46] = 0; // interactibleBasicWeapon_obj
global.__objectDepths[47] = 0; // interactibleWeaponSpinner_obj
global.__objectDepths[48] = 0; // interactibleWeaponHeavyWeaponry_obj
global.__objectDepths[49] = 0; // interactibleWeaponTheWatcher_obj
global.__objectDepths[50] = 0; // interactibleWeaponShotgun_obj
global.__objectDepths[51] = 0; // interactibleWeaponRoguishBlaster_obj
global.__objectDepths[52] = 0; // interactibleWeaponRudimentaryLaser_obj
global.__objectDepths[53] = 0; // interactibleWeaponMitosinNagant_obj
global.__objectDepths[54] = 0; // interactibleWeaponM4A1_obj
global.__objectDepths[55] = 0; // interactibleWeaponAN94_obj
global.__objectDepths[56] = 0; // interactibleWeaponAA12_obj
global.__objectDepths[57] = 0; // interactibleWeaponMA5B_obj
global.__objectDepths[58] = 0; // entityWeaponBase_obj
global.__objectDepths[59] = 0; // entityWeaponBulletBase_obj
global.__objectDepths[60] = 0; // entityWeaponTest_obj
global.__objectDepths[61] = 0; // entityWeaponShotgun_obj
global.__objectDepths[62] = 0; // entityWeaponAA12_obj
global.__objectDepths[63] = 0; // entityWeaponSpinner_obj
global.__objectDepths[64] = 0; // entityWeaponHeavyWeaponry_obj
global.__objectDepths[65] = 0; // entityWeaponM4A1_obj
global.__objectDepths[66] = 0; // entityWeaponMA5B_obj
global.__objectDepths[67] = 0; // entityWeaponAN94_obj
global.__objectDepths[68] = 0; // entityWeaponMitosinNagant_obj
global.__objectDepths[69] = 0; // entityWeaponLaserBase_obj
global.__objectDepths[70] = 0; // entityWeaponRoguishBlaster_obj
global.__objectDepths[71] = 0; // entityWeaponRudimentaryLaser_obj
global.__objectDepths[72] = 0; // entityWeaponBaddieTest_obj
global.__objectDepths[73] = 0; // entityWeaponTheWatcher_obj
global.__objectDepths[74] = 0; // entityHands_obj
global.__objectDepths[75] = 0; // playerHands_obj
global.__objectDepths[76] = 0; // serverClientBase_obj
global.__objectDepths[77] = 0; // server_obj
global.__objectDepths[78] = 0; // serverTest_obj
global.__objectDepths[79] = 0; // serverLobby_obj
global.__objectDepths[80] = 0; // clientBase_obj
global.__objectDepths[81] = 0; // clientTest_obj
global.__objectDepths[82] = 0; // clientLobby_obj
global.__objectDepths[83] = 0; // clientSession_obj
global.__objectDepths[84] = 0; // networkOutbox_obj
global.__objectDepths[85] = 0; // ipProbe_obj
global.__objectDepths[86] = 0; // debug_obj
global.__objectDepths[87] = 0; // damage_display_obj
global.__objectDepths[88] = 0; // playerStatDisplay_obj
global.__objectDepths[89] = 0; // projDummy_obj
global.__objectDepths[90] = 0; // testBounceyBall_obj
global.__objectDepths[91] = 0; // RotatorTest_obj
global.__objectDepths[92] = 0; // LoggerCloseListener_obj
global.__objectDepths[93] = 0; // gui_element_obj
global.__objectDepths[94] = 0; // uiButtonBase_obj
global.__objectDepths[95] = 0; // uiButtonGeneric_obj
global.__objectDepths[96] = 0; // uiButtonCreateGame_obj
global.__objectDepths[97] = 0; // uiButtonJoinGame_obj
global.__objectDepths[98] = 0; // ui_cursor_obj
global.__objectDepths[99] = 0; // uiCursorGeneric_obj
global.__objectDepths[100] = 0; // testGameListTest_obj
global.__objectDepths[101] = 0; // list_section_header_obj
global.__objectDepths[102] = 0; // listViewGameList_obj
global.__objectDepths[103] = 0; // list_view_obj
global.__objectDepths[104] = 0; // list_item_obj
global.__objectDepths[105] = 0; // listView_obj
global.__objectDepths[106] = 0; // listGroup_obj
global.__objectDepths[107] = 0; // listItem_obj
global.__objectDepths[108] = 0; // ui_container_obj
global.__objectDepths[109] = 0; // ui_container_basic_obj
global.__objectDepths[110] = 0; // uiContainerGameList_obj
global.__objectDepths[111] = 0; // uiContainerGameSession_obj
global.__objectDepths[112] = 0; // uiLabel_obj
global.__objectDepths[113] = 0; // gameController_obj
global.__objectDepths[114] = 0; // gameControllerLobbyServer_obj
global.__objectDepths[115] = 0; // roomController_obj
global.__objectDepths[116] = 0; // frameSpeedModCalculator_obj
global.__objectDepths[117] = 0; // environmentBase_obj
global.__objectDepths[118] = 0; // environmentNetworked_obj
global.__objectDepths[119] = 0; // environmentWall_obj
global.__objectDepths[120] = 0; // environmentWallRepresentation_obj
global.__objectDepths[121] = 0; // environmentWallAlienSide_obj
global.__objectDepths[122] = 0; // environmentWallAlienBack_obj
global.__objectDepths[123] = 0; // environmentWallAlien_obj
global.__objectDepths[124] = 0; // environmentDoor_obj
global.__objectDepths[125] = 0; // impactBase_obj
global.__objectDepths[126] = 0; // impactHitWall_obj
global.__objectDepths[127] = 0; // impactHitEntity_obj
global.__objectDepths[128] = 0; // casing_obj
global.__objectDepths[129] = 0; // casingShotgun_obj
global.__objectDepths[130] = 0; // casingBig_obj
global.__objectDepths[131] = 0; // casingRifle_obj
global.__objectDepths[132] = 0; // clip_obj
global.__objectDepths[133] = 0; // MuzzleFlashAssaultRifle_obj
global.__objectDepths[134] = 0; // backgroundWorker_obj
global.__objectDepths[135] = 0; // EventTest
global.__objectDepths[136] = 0; // Editable_obj
global.__objectDepths[137] = 0; // Editor_obj
global.__objectDepths[138] = 0; // console_obj
global.__objectDepths[139] = 0; // FormsInputController_obj
global.__objectDepths[140] = 0; // FormsElementBase_obj
global.__objectDepths[141] = 0; // FormsPanelTest_obj
global.__objectDepths[142] = 0; // FormsPanelWithinPanelTest_obj
global.__objectDepths[143] = 0; // FormsPanelWithinPanelWithinPanelTest_obj
global.__objectDepths[144] = 0; // FormsTextDisplayBase_obj
global.__objectDepths[145] = 0; // TextDisplayTest_obj
global.__objectDepths[146] = 0; // HitboxHitter_obj
global.__objectDepths[147] = 0; // HitboxHittee_obj
global.__objectDepths[148] = 0; // HitSpine_obj


global.__objectNames[0] = "entity_obj";
global.__objectNames[1] = "entityLocal_obj";
global.__objectNames[2] = "entityNetwork_obj";
global.__objectNames[3] = "entityNetworkPrime_obj";
global.__objectNames[4] = "entityNetworkShadow_obj";
global.__objectNames[5] = "Movable_obj";
global.__objectNames[6] = "Collidable_obj";
global.__objectNames[7] = "CollidingMover_obj";
global.__objectNames[8] = "CollidingMoverTest_obj";
global.__objectNames[9] = "CollidingMoverWallCollider_obj";
global.__objectNames[10] = "MovableTest_obj";
global.__objectNames[11] = "entityCombatant_obj";
global.__objectNames[12] = "entityCombatantShadow_obj";
global.__objectNames[13] = "entityCombatantFriendly_obj";
global.__objectNames[14] = "playerBase_obj";
global.__objectNames[15] = "playerBasic_obj";
global.__objectNames[16] = "player1_obj";
global.__objectNames[17] = "player1Test_obj";
global.__objectNames[18] = "entityCombatantEnemy_obj";
global.__objectNames[19] = "entityCombatantEnemyShadow_obj";
global.__objectNames[20] = "entityEnemyTest_obj";
global.__objectNames[21] = "projectileBase_obj";
global.__objectNames[22] = "projectileFriendly_obj";
global.__objectNames[23] = "projectileEnemy_obj";
global.__objectNames[24] = "projectileEnemyShadow_obj";
global.__objectNames[25] = "projectileFriendlyShadow_obj";
global.__objectNames[26] = "projectileTick_obj";
global.__objectNames[27] = "projectileShotgunPellet_obj";
global.__objectNames[28] = "projectileSpinner_obj";
global.__objectNames[29] = "projectileHour_obj";
global.__objectNames[30] = "projectileBaddieBasic_obj";
global.__objectNames[31] = "projectileBulletBase_obj";
global.__objectNames[32] = "projectileBulletHighSpeedBase_obj";
global.__objectNames[33] = "projectileTest_obj";
global.__objectNames[34] = "projectileHighSpeedTest_obj";
global.__objectNames[35] = "projectileHighSpeedInvisible_obj";
global.__objectNames[36] = "projectileLaserBase_obj";
global.__objectNames[37] = "projectileLaser_obj";
global.__objectNames[38] = "projectileLaserBeamBase_obj";
global.__objectNames[39] = "interactibleShadow_obj";
global.__objectNames[40] = "interactibleBase_obj";
global.__objectNames[41] = "item_obj";
global.__objectNames[42] = "itemPassiveBase_obj";
global.__objectNames[43] = "passiveDrumMag_obj";
global.__objectNames[44] = "passivePurplePowder_obj";
global.__objectNames[45] = "passiveAlienAutopsy_obj";
global.__objectNames[46] = "interactibleBasicWeapon_obj";
global.__objectNames[47] = "interactibleWeaponSpinner_obj";
global.__objectNames[48] = "interactibleWeaponHeavyWeaponry_obj";
global.__objectNames[49] = "interactibleWeaponTheWatcher_obj";
global.__objectNames[50] = "interactibleWeaponShotgun_obj";
global.__objectNames[51] = "interactibleWeaponRoguishBlaster_obj";
global.__objectNames[52] = "interactibleWeaponRudimentaryLaser_obj";
global.__objectNames[53] = "interactibleWeaponMitosinNagant_obj";
global.__objectNames[54] = "interactibleWeaponM4A1_obj";
global.__objectNames[55] = "interactibleWeaponAN94_obj";
global.__objectNames[56] = "interactibleWeaponAA12_obj";
global.__objectNames[57] = "interactibleWeaponMA5B_obj";
global.__objectNames[58] = "entityWeaponBase_obj";
global.__objectNames[59] = "entityWeaponBulletBase_obj";
global.__objectNames[60] = "entityWeaponTest_obj";
global.__objectNames[61] = "entityWeaponShotgun_obj";
global.__objectNames[62] = "entityWeaponAA12_obj";
global.__objectNames[63] = "entityWeaponSpinner_obj";
global.__objectNames[64] = "entityWeaponHeavyWeaponry_obj";
global.__objectNames[65] = "entityWeaponM4A1_obj";
global.__objectNames[66] = "entityWeaponMA5B_obj";
global.__objectNames[67] = "entityWeaponAN94_obj";
global.__objectNames[68] = "entityWeaponMitosinNagant_obj";
global.__objectNames[69] = "entityWeaponLaserBase_obj";
global.__objectNames[70] = "entityWeaponRoguishBlaster_obj";
global.__objectNames[71] = "entityWeaponRudimentaryLaser_obj";
global.__objectNames[72] = "entityWeaponBaddieTest_obj";
global.__objectNames[73] = "entityWeaponTheWatcher_obj";
global.__objectNames[74] = "entityHands_obj";
global.__objectNames[75] = "playerHands_obj";
global.__objectNames[76] = "serverClientBase_obj";
global.__objectNames[77] = "server_obj";
global.__objectNames[78] = "serverTest_obj";
global.__objectNames[79] = "serverLobby_obj";
global.__objectNames[80] = "clientBase_obj";
global.__objectNames[81] = "clientTest_obj";
global.__objectNames[82] = "clientLobby_obj";
global.__objectNames[83] = "clientSession_obj";
global.__objectNames[84] = "networkOutbox_obj";
global.__objectNames[85] = "ipProbe_obj";
global.__objectNames[86] = "debug_obj";
global.__objectNames[87] = "damage_display_obj";
global.__objectNames[88] = "playerStatDisplay_obj";
global.__objectNames[89] = "projDummy_obj";
global.__objectNames[90] = "testBounceyBall_obj";
global.__objectNames[91] = "RotatorTest_obj";
global.__objectNames[92] = "LoggerCloseListener_obj";
global.__objectNames[93] = "gui_element_obj";
global.__objectNames[94] = "uiButtonBase_obj";
global.__objectNames[95] = "uiButtonGeneric_obj";
global.__objectNames[96] = "uiButtonCreateGame_obj";
global.__objectNames[97] = "uiButtonJoinGame_obj";
global.__objectNames[98] = "ui_cursor_obj";
global.__objectNames[99] = "uiCursorGeneric_obj";
global.__objectNames[100] = "testGameListTest_obj";
global.__objectNames[101] = "list_section_header_obj";
global.__objectNames[102] = "listViewGameList_obj";
global.__objectNames[103] = "list_view_obj";
global.__objectNames[104] = "list_item_obj";
global.__objectNames[105] = "listView_obj";
global.__objectNames[106] = "listGroup_obj";
global.__objectNames[107] = "listItem_obj";
global.__objectNames[108] = "ui_container_obj";
global.__objectNames[109] = "ui_container_basic_obj";
global.__objectNames[110] = "uiContainerGameList_obj";
global.__objectNames[111] = "uiContainerGameSession_obj";
global.__objectNames[112] = "uiLabel_obj";
global.__objectNames[113] = "gameController_obj";
global.__objectNames[114] = "gameControllerLobbyServer_obj";
global.__objectNames[115] = "roomController_obj";
global.__objectNames[116] = "frameSpeedModCalculator_obj";
global.__objectNames[117] = "environmentBase_obj";
global.__objectNames[118] = "environmentNetworked_obj";
global.__objectNames[119] = "environmentWall_obj";
global.__objectNames[120] = "environmentWallRepresentation_obj";
global.__objectNames[121] = "environmentWallAlienSide_obj";
global.__objectNames[122] = "environmentWallAlienBack_obj";
global.__objectNames[123] = "environmentWallAlien_obj";
global.__objectNames[124] = "environmentDoor_obj";
global.__objectNames[125] = "impactBase_obj";
global.__objectNames[126] = "impactHitWall_obj";
global.__objectNames[127] = "impactHitEntity_obj";
global.__objectNames[128] = "casing_obj";
global.__objectNames[129] = "casingShotgun_obj";
global.__objectNames[130] = "casingBig_obj";
global.__objectNames[131] = "casingRifle_obj";
global.__objectNames[132] = "clip_obj";
global.__objectNames[133] = "MuzzleFlashAssaultRifle_obj";
global.__objectNames[134] = "backgroundWorker_obj";
global.__objectNames[135] = "EventTest";
global.__objectNames[136] = "Editable_obj";
global.__objectNames[137] = "Editor_obj";
global.__objectNames[138] = "console_obj";
global.__objectNames[139] = "FormsInputController_obj";
global.__objectNames[140] = "FormsElementBase_obj";
global.__objectNames[141] = "FormsPanelTest_obj";
global.__objectNames[142] = "FormsPanelWithinPanelTest_obj";
global.__objectNames[143] = "FormsPanelWithinPanelWithinPanelTest_obj";
global.__objectNames[144] = "FormsTextDisplayBase_obj";
global.__objectNames[145] = "TextDisplayTest_obj";
global.__objectNames[146] = "HitboxHitter_obj";
global.__objectNames[147] = "HitboxHittee_obj";
global.__objectNames[148] = "HitSpine_obj";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for